all:
  hosts:
    svrancherp1:
      ansible_host: 10.10.22.120
  children:
    application_rancher:
      hosts:
        svrancherp1:
    os_suse_microos:
      hosts:
        svrancherp1:
    provider_terraform:
      hosts:
        svrancherp1:
