"svrancherp1":
  "cloud_init_file_id": "local:snippets/user.cloud-config-svrancherp1.yaml"
  "hostname": "svrancherp1"
  "ipv4_address": "10.10.22.120/24"
  "tags":
  - "application-rancher"
  - "os-suse_microos"
  - "provider-terraform"
  "vm_id": 100
